version: 1.1.1.{build}

branches:
  only:
    - main

skip_tags: true
max_jobs: 1

environment:
  signtool: C:\Program Files (x86)\Windows Kits\10\bin\10.0.18362.0\x64\signtool.exe
  pfx_secret:
    secure: 2NVW7WO5tvFaSNL2xOiPHgtAChdB0tg7/xd3nYSHa5g=
  pfx_salt:
    secure: AuGPavXVWeeE9hjJApCiQ/u4tYhtFiblJp0T0SA9SGQ52s+lFQfEIAgllaXhBpQqiQE4tm72xILn188fa7mniw==
  pfx_pass:
    secure: MwHaN8/HEjEae4hmf8FwZg==

install:
  - ps: iex ((New-Object Net.WebClient).DownloadString('https://raw.githubusercontent.com/appveyor/secure-file/master/install.ps1'))
  - cmd: appveyor-tools\secure-file -decrypt sectigo.pfx.enc -secret %pfx_secret% -salt %pfx_salt%

artifacts:
  - path: 'SquadsV\bin\Debug\SquadsV.dll'

after_build:
  - cmd: |
      "%SIGNTOOL%" sign /t http://timestamp.sectigo.com /f sectigo.pfx /p %pfx_pass% "%APPVEYOR_BUILD_FOLDER%\SquadsV\bin\Debug\SquadsV.dll" && "%SIGNTOOL%" sign /tr http://timestamp.sectigo.com /td sha256 /f sectigo.pfx /fd sha256 /p %pfx_pass% /as "%APPVEYOR_BUILD_FOLDER%\SquadsV\bin\Debug\SquadsV.dll"